#!/bin/sh

if [ -z ${OVS_BIN} ]; then
  OVS_BIN='/usr/local/bin'
else 
  echo "using OVS_ROOT of ${OVS_BIN}"
fi

if [ -z ${OVS_SBIN} ]; then
  OVS_SBIN='/usr/local/sbin'
else 
  echo "using OVS_ROOT of ${OVS_SBIN}"
fi

switch='br0'
/sbin/ifconfig $1 0.0.0.0 up
${OVS_BIN}/ovs-vsctl add-port ${switch} $1
